# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Github Pull Request

on:
  pull_request:
    branches: [ main]
  push:
    branches: [ main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        server-id: github
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: ./mvnw -B package -Pproduction --file pom.xml

    - name: Run tests
      run: ./mvnw -B test --file pom.xml